channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- mkl
- tensorflow
# pytorch
- cudnn
- nccl
- transformers
- sentencepiece
- pytorch-lightning
# data science
- pandas
- numpy
- pyarrow
- matplotlib
- seaborn
- scikit-learn
