program: cfq/train.py
method: random
metric:
  name: valid/emr/dataloader_idx_0
  goal: maximize
parameters:
  # configurable parameters
  num_epochs:
    value: 100
  sweep_mode:
    value: True
  wandb_project:
    value: final_eval_icml
  run_dir_root:  # cache data in RAM
    value: /data/paras/data_cache/cfq
  cfq_split:
    value: mcd3
  optimizer_name:
    distribution: categorical
    values:
    - Adam
    - AdamW
  batch_size:
    distribution: categorical
    values:
    - 128
    - 256
    - 512
    - 1024
  lr:
    distribution: uniform
    min: 0.001
    max: 0.01

  # training parameters to sweep
  warmup_epochs:
    distribution: int_uniform
    min: 0
    max: 20
  cosine_lr_period:
    distribution: uniform
    min: 0
    max: 0.5
  gradient_clip_val:
    distribution: categorical
    values:
    - 0
    - 5.

  # architectural parameters to sweep
  dropout:
    distribution: uniform
    min: 0.
    max: 0.5
  seq_inp:
    distribution: categorical
    values:
    - 16
    - 32
    - 64
  seq_hidden_dim:
    distribution: categorical
    values:
    - 64
    - 128
  seq_nlayers:
    distribution: categorical
    values:
    - 3
    - 4